# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
   
    - name: Install dependencies
      run: |
          sudo apt-get install xvfb
          PUPPETEER_PRODUCT=firefox npm install
          npm install

    - name: Build
      run: npm run build

    - name: Run test
      run: npm run test:e2e

    # - name: Cache dependencies
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.cache/yarn
    #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-yarn-

    # - run: yarn install --frozen-lockfile
    # - run: yarn add puppeteer jest-puppeteer
    # - run: yarn run test:e2e